### ISSUE TITLE
java.lang.Exception: Stack trace

### ISSUE THREAD

**Issue by halfchen** [CoderToPM/scrcpyConnectNode#6]
C:\Users\admin>adb push D:\scrcpy-server.jar /data/local/tmp/
D:\scrcpy-server.jar: 1 file pushed, 0 skipped. 219.3 MB/s (742855 bytes in 0.003s)

C:\Users\admin>adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 8000000 true 1080:1920:0:0 true true
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Thread.java:1348)
        at com.genymobile.scrcpy.Server.main(Server.java:125)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 5 parameters
        at com.genymobile.scrcpy.Server.createOptions(Server.java:66)
        at com.genymobile.scrcpy.Server.main(Server.java:157)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by halfchen** [comment]
执行adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 0 8000000 true 1080:1920:0:0 true true
报错后，/data/local/tmp/路径下的scrcpy-server.jar也被删除了，再次push后执行下一步还是报错。
